export interface UsageRecord {
  id: string;
  userId: string;
  conversationId: string | null;
  messageId: string | null;
  requestId: string | null;
  modelId: string;
  agentSlug: string;
  modelProvider: string;
  platform: string;
  status: string;
  interactionMode: "auto" | "agent";
  errorCode: string | null;
  latencyMs: number;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  creditsDeducted: number;
  estimatedCredits: number | null;
  walletBalanceBefore: number | null;
  walletBalanceAfter: number | null;
  actualCostUsd: number | null;
  finishReason: string | null;
  semanticCacheHit: boolean;
  promptCacheHit?: boolean;
  hadFiles: boolean;
  hadVoice: boolean;
  routerLatencyMs: number | null;
  cacheHitLayer: string | null;
  webSearchEngine: string | null;
  webSearchCount: number;
  webFetchCount: number;
  toolCountTotal: number;
  webSearchUsed: boolean;
  codeExecutionUsed: boolean;
  codeExecutionCount: number;
  inputTokensFresh: number | null;
  inputTokensCached: number | null;
  cacheWriteTokens: number | null;
  metadata: Record<string, unknown>;
  ipHash: string | null;
  userAgent: string | null;
  createdAt: string;
}

export interface RecordUsageArgs {
  userId: string;
  conversationId?: string | null;
  messageId?: string | null;
  requestId?: string | null;
  modelId: string;
  agentSlug: string;
  modelProvider: string;
  platform: string;
  status: "success" | "failed" | "cancelled" | "timeout";
  interactionMode?: "auto" | "agent";
  errorCode?: string | null;
  latencyMs: number;
  /** Total input tokens (fresh + cached); used for rollup when detailed columns omitted */
  inputTokens: number;
  outputTokens: number;
  creditsDeducted: number;
  estimatedCredits?: number | null;
  walletBalanceBefore?: number | null;
  walletBalanceAfter?: number | null;
  actualCostUsd?: number | null;
  finishReason?: string | null;
  semanticCacheHit?: boolean;
  promptCacheHit?: boolean;
  hadFiles?: boolean;
  hadVoice?: boolean;
  ip?: string | null;
  userAgent?: string | null;
  routerLatencyMs?: number | null;
  cacheHitLayer?: string | null;
  webSearchEngine?: string | null;
  webSearchCount?: number | null;
  webFetchCount?: number | null;
  toolCountTotal?: number | null;
  webSearchUsed?: boolean | null;
  codeExecutionUsed?: boolean | null;
  codeExecutionCount?: number | null;
  inputTokensFresh?: number | null;
  inputTokensCached?: number | null;
  cacheWriteTokens?: number | null;
  metadata?: Record<string, unknown> | null;
  llmFirstTokenMs?: number | null;
  llmTotalMs?: number | null;
}
