from Brain.shared.build_standards import (
    GLOBAL_BUILD_STANDARDS,
    FRONTEND_BUILD_STANDARDS,
    BACKEND_BUILD_STANDARDS,
    DATABASE_BUILD_STANDARDS,
    INTEGRATION_BUILD_STANDARDS,
    TASK_ORDER_STANDARDS,
    FULL_STACK_BUILD_STANDARDS,  # backward compatibility
    INTEGRATION_TASK_TEMPLATE,
)

__all__ = [
    "GLOBAL_BUILD_STANDARDS",
    "FRONTEND_BUILD_STANDARDS",
    "BACKEND_BUILD_STANDARDS",
    "DATABASE_BUILD_STANDARDS",
    "INTEGRATION_BUILD_STANDARDS",
    "TASK_ORDER_STANDARDS",
    "FULL_STACK_BUILD_STANDARDS",
    "INTEGRATION_TASK_TEMPLATE",
]
